local pp = require( 'pp' )

pp[[
// DO NOT EDIT BY HAND, AUTOGENERATED CONTENT
// Bindings for raylib https://github.com/raysan5/raylib
// Generator by iskolbin https://github.com/iskolbin/lraylib-gen

#define LUA_LIB
#include <stdlib.h>
#include <string.h>
#include "raylib.h"
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

#define ISL_SLEEP_IMPLEMENTATION
#include "isl_sleep/isl_sleep.h"

static int isl_Sleep(lua_State *L) {
  int us = luaL_checkinteger(L, -1);
  isl_usleep(us);
  return 0;
}]]
