local pp = require( 'pp' )

pp[[
// DO NOT EDIT BY HAND, AUTOGENERATED CONTENT
// Bindings for raylib https://github.com/raysan5/raylib
// Generator by iskolbin https://github.com/iskolbin/lraylib-gen

#define LUA_LIB
#include <stdlib.h>
#include <string.h>
#include "raylib.h"
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

static void raylua_register_metatable(lua_State *L, const luaL_Reg *l) {
#if LUA_VERSION_NUM <= 501
	luaL_register(L, NULL, l);
#else
	luaL_setfuncs(L, l, 0);
#endif
}

#define ISL_SLEEP_IMPLEMENTATION
#include "isl_sleep/isl_sleep.h"

static int isl_Sleep(lua_State *L) {
  int us = luaL_checkinteger(L, -1);
  isl_usleep(us);
  return 0;
}]]
